# Generated by Django 5.2 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='prix_par_nuit',
        ),
        migrations.RemoveField(
            model_name='maison',
            name='titre',
        ),
        migrations.AddField(
            model_name='maison',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='maison',
            name='adresse',
            field=models.CharField(max_length=255),
        ),
    ]
