# Generated by Django 5.2 on 2025-05-23 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_client_email_client_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='maison',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maison',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maisons/'),
        ),
        migrations.AlterField(
            model_name='maison',
            name='prix',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
